FROM golang:1.20 AS builder

ARG REF
ARG GO_COMMIT_REF
WORKDIR /go/src/github.com/stellar/go
RUN git clone https://github.com/anupsdf/go /go/src/github.com/stellar/go
RUN git fetch origin ${GO_COMMIT_REF}
RUN git checkout ${GO_COMMIT_REF}
ENV CGO_ENABLED=0
ENV GOFLAGS="-ldflags=-X=github.com/stellar/go/support/app.version=${REF}-(built-from-source)"
RUN go install github.com/stellar/go/services/horizon
